### ISSUE TITLE
TypeError: Cannot read property 'transport' of undefined

### ISSUE THREAD

**Issue by neutron450** [reelyactive/hlc-server#5]
Hello, I'm encountering the following error when trying to start the hlc-server.
I've tried a few different distros--xubuntu, ubuntu and mint all with the exact same error.
Any guidance would be greatly appreciated!

reelyactive@reelyactive:~/reelyActive/hlc-server$ npm start

> hlc-server@1.0.24 start /home/reelyactive/reelyActive/hlc-server
> node bin/hlc-server

reelyActive barnowl instance is listening for an open IoT
/home/reelyactive/reelyActive/hlc-server/node_modules/@elastic/elasticsearch/api/api/ping.js:47
  return this.transport.request(request, options, callback)
              ^

TypeError: Cannot read property 'transport' of undefined
    at pingApi (/home/reelyactive/reelyActive/hlc-server/node_modules/@elastic/elasticsearch/api/api/ping.js:47:15)
    at retryUntilSuccess (/home/reelyactive/reelyActive/hlc-server/lib/elasticmanager.js:122:3)
    at ElasticManager.notifyOnElasticsearchRunning (/home/reelyactive/reelyActive/hlc-server/lib/elasticmanager.js:43:5)
    at new HLCServer (/home/reelyactive/reelyActive/hlc-server/lib/hlcserver.js:99:18)
    at Object.<anonymous> (/home/reelyactive/reelyActive/hlc-server/bin/hlc-server:10:11)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hlc-server@1.0.24 start: `node bin/hlc-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hlc-server@1.0.24 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/reelyactive/.npm/_logs/2020-09-29T14_34_51_069Z-debug.log

**Comment by jeffyactive** [comment]
Hi @neutron450, it looks like the Elasticsearch package is throwing an error.  First time we see this issue.  Can you try to manually install an earlier version of the Elasticsearch package?  For instance:
`npm install @elastic/elasticsearch@7.9.0`

and then run again to see if the error persists?  Please also advise of your Node.js version, which could be a factor:
`node --version`

**Comment by neutron450** [comment]
Success, 7.9.0 starts up with no errors.
I tried node ver 10.15.3 & 12.18.4 - both gave the same error.
Thank you!

**Comment by jeffyactive** [comment]
Glad that did the trick.  Likely a bug in the latest version of the Elasticsearch package which hopefully will be corrected by Elastic in the next version.  Enjoy hlc-server!  Closing the issue.
